# Generated by Django 3.0.2 on 2020-01-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.CharField(max_length=50)),
                ('measured_depth', models.FloatField(max_length=10)),
                ('inclination', models.FloatField(max_length=10)),
                ('azimuth', models.FloatField(max_length=10)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.Well')),
            ],
        ),
    ]
